apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: routingdb-pvc-claim
  namespace: cargotracker-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ibmc-block-silver
