apiVersion: v1
data:
  routingdb.user.name: {{ .Values.credentials.dbusername }}
  routingdb.user.password: {{ .Values.credentials.dbpassword }}
  rabbitmq.user.name: {{ .Values.credentials.mqusername }}
  rabbitmq.user.password: {{ .Values.credentials.mqpassword }}   
kind: Secret
metadata:
  name: cargotracker-routing-credentials
type: Opaque